### PR TITLE
add args_no_hyphens, args_json, args_json_file to sweep command

### PR DESCRIPTION
**Pull request by raubitsj**
WB-3359 #close add args_no_hyphens to sweep command

User request: https://wandb.atlassian.net/browse/WB-3359

### CODE REVIEW

**Review by vanpelt — COMMENTED** [review]
May as well add args_json while we're at it 😎

**Comment by raubitsj** [comment]
Sure. That was the plan eventually.

I wasn't sure how people would want it tho.

I'll add args_json and args_json_file
Where the latter writes a file and gives you back the filename

**Comment by raubitsj** [comment]
> May as well add args_json while we're at it 😎

Added, please take another look

This sweep config is fun:
```
program: train-no-hyphens.py
method: grid
# Parameters to search over
parameters:
  optimizer:
    values: ["sgd", "adam"]
  flag1:
    values:
    - false
    - true
  flag2:
    values:
    - false
    - true
command:
    - ${env}
    - python
    - ${program}
    - ${args_no_hyphens}
    - ${args}
    - ${args_json}
    - ${args_json_file}
```

The filename is relative right now.  which i think is fine, but could cause some issues,  I want to leave it that way until looking into file path issues (there is a ticket for it already)

**Review by vanpelt — APPROVED** [review]
Sick!

**Pull request merged**
